name: CD Production

on:
  workflow_run:
    workflows: ["CI - MERN VC App"]
    types:
      - completed

jobs:
  deploy-prod:
    name: Build & Deploy Prod Images
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Pull Prod Image
        run: docker pull ghcr.io/${{ github.actor }}/vc-server:prod-${{ github.sha }}

      - name: Trigger Render Production Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVER_SERVICE_ID: ${{ secrets.RENDER_SERVER_SERVICE_ID }}
        run: |
          curl -X POST https://api.render.com/v1/services/$SERVER_SERVICE_ID/deploys \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -d '{}'
